services:
  mongodb:
    image: mongo:8
    container_name: campusinterview-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: campusinterview
      GLIBC_TUNABLES: glibc.cpu.hwcaps=-SHSTK
    volumes:
      - mongodb_data:/data/db

  rustfs:
    image: rustfs/rustfs:latest-glibc
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin
    volumes:
      - rustfs_data:/data
    user: "10001:10001"
    
  # for developing reason the old postgresql database and viewer
  postgres:
    image: postgres:16
    container_name: campusinterview-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: campusinterview
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: campusinterview-pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  mongodb_data:
  rustfs_data:
  postgres_data:
  pgadmin_data:
